---
title: "Project 3 - Urban Ministries of Durham"
author: "Jesus E. Vazquez"
date: "11/18/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

### Background Description

Urban Ministries of Durham assist around 6,000 people each year who need food, shelter, clothing and/or supportive services. Some of the programs that they offer is a (1) community shelter where people are given a place to sleep and assistance to help them find a home, a (2) Community Café that serves three meals a day, seven days a week, 365 days a year, and a (3) food and clothing closet for those that either need food or clothing. 

### Motivation

Just as with any other organization, validation of the organization efforts is needed to understand if Urban Minisitries of Durham is doing a good job at helping people transform their lives. Having this information at hand when meeting with donors can give a sense of security that their donations are not going to waste. Not only are the efforts of counselors into helping homeless find a home important but one should also consider how finances are being managed at the homesless shelter. For this reason the tax records will be examined to show if there are any signs of fradulent behavior. To inspect the work of counselors, this project will examine if the shelter reduces the number of diabilities reported by new-incomers by the time they find a home.

### Approach

To determine the financial performance of the organization from the Urban Ministries of Durham the first digit of the net income, expenses and income-expenses will be considered. Theoretically, this should follow a Bendford distribution and any deviations from this distribution would suggest fabricated numbers. For the second part of the project, we will count the number of patients that came in with a condition (e.g. - mental health problem) and left with (1) none, (2) the same, or (3) with more problems. The distribution of ages among those who got a disability while at the UMD will be plotted using boxplots, stratified by condition.

# Results 

### Urban Ministries of Durham is not guilty of fraud

Determine the financial performance of the organization from the Urban Ministries of Durham the first digit of the net income (income minus expenses) will be considered. Theoretically, this should follow a Bendford distribution and any deviations from this distribution would suggest fabricated numbers. In practice this tests requires more than 50 observations but in this case we only had 12, but we validated results using small sample theory. The following are the statistical results.

**Large Sample Theory**

```
Chi-squared Test Statistic = 9.500
Critical value at a P-value of 0.05 is 15.51.
```

Using large sample theory as chi-square was calculated. Since our chi-square test statistic of 9.50 was less than the critical calue of 15.15 we fail to reject the null hypothesis. We conclude that the income tax data from Urban Ministries of Durham does not provide sufficient evidence to claim that the non-for-profit engages in fraudulent behavior when reporting taxes. One of the the limitations from this analysis was that we had few observations. One of the recommendations for the test is to have at least 50 obs but in this case we had only 12. 

**Small Sample Theory** 

```
actual counts are [4, 0, 1, 1, 3, 2, 0, 1, 0]
expected counts are [4, 2, 2, 1, 1, 1, 1, 1, 1]
Mannwhitney Result: (statistic=32.5, pvalue=0.2384481543359947)
```

Since n is small we will be using the Wilcoxon Rank Sum Test to verify that the two distributions are identical.Just as with the Chi-Square test, the Wilcoxon Rank Sum Test shows that the data does not provide sufficient data to reject the assumption that the expected and the observed values follows the same distribution. We can conclude that the income tax reports from Urban Ministries of Durham do not provide sufficient data to suggest that the non-for-profit engaged in disingenuous tax filing behavior. The following is a graphical representation on how the the two distributions compare.

```{R echo = FALSE, message = FALSE, warning = FALSE}
## Import Data
library(tidyverse)
library(ggplot2)

my_tax_data = read_csv("C:\\Users\\15056\\Documents\\BIOS611\\bios611-projects-fall-2019-jvazquez2\\project_3\\data\\tax_data_graph.csv")

tax_plot = ggplot(data=my_tax_data, aes(x=Number, y=value, fill=variable)) +
  geom_bar(stat="identity", color="black", position=position_dodge()) + theme_minimal() +
  labs(title = "Urban Ministries of Durham - 2006-2018 Tax Fraud Analysis", subtitle = 'Net-Income', y = 'Percentage (%)', fill = "Group") +
  scale_x_continuous("Digit", labels = as.character(my_tax_data$Number), breaks = my_tax_data$Number)

print(tax_plot)
```

### Low Levels of Disability Cases while at UMD 

The following is a graph illstrating the distribution of age per disability developed while at UMD.

```{R echo = FALSE, message = FALSE, warning = FALSE}
my_patient_data = read_csv("C:\\Users\\15056\\Documents\\BIOS611\\bios611-projects-fall-2019-jvazquez2\\project_3\\data\\patients_data_graph.csv")

patient_plot = ggplot(my_patient_data, aes(x=my_patient_data$`Disability Type`, y = my_patient_data$`Client Age at Entry`)) +
  geom_boxplot(fill='#00BFC4') +
  theme_minimal() +  
  labs(title = "Distributions of Age for Patients who got a Disability while at UMD", subtitle = 'Per type of Disability', y = 'Age', x = 'Disability Type') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(patient_plot)
```
We can observe that Mental Health Problems is a problem that affects people of a variety of ages at UMD. Efforts should be placed at helping residents deal with the trauma and hardship that they're going through.The following table illustrates the number cases stratified by gender.

```
Client Gender  Disability Type                  
Female         Both Alcohol and Drug Abuse (HUD)    1
               Chronic Health Condition (HUD)       3
               HIV/AIDS (HUD)                       1
               Mental Health Problem (HUD)          8
               Physical (HUD)                       5
Male           Alcohol Abuse (HUD)                  2
               Both Alcohol and Drug Abuse (HUD)    2
               Chronic Health Condition (HUD)       4
               Developmental (HUD)                  1
               Drug Abuse (HUD)                     2
               HIV/AIDS (HUD)                       1
               Mental Health Problem (HUD)          6
               Physical (HUD)                       2
```

## Conclusions

Overall good performance, both at the administrative financial side of the UMD and at the counselors levels. Next steps should be aimed at creating activities that target mental-health.
